### ISSUE TITLE
Script placement in Html??

### ISSUE THREAD

**Issue by ifiokabasibom** [nodejsafrica/workshoppers#6]
Where exactly is the best place to put your JavaScript in your html code? cos I've seen some article that says you should put it in the head if you want the script to run on some event such as a button click else it should be in the body, and even in the body some say it should just before </body> so the page can load faster. I'm really confused atm. And also why is it that sometimes the script is saved as an external file and referenced externally in the head like it's done with external css?? please someone should explain these things so I don't end up confusing myself the more

**Comment by codeekage** [comment]
Yea, most times the `<script></script>` is placed in the head, probably you want to run a function or do something before the entire page loads, and it's good practice to place to the  `<script></script>` in the `<body></body>` that way, it loads faster and elements you've probably selected to work with must have been loaded before executing your scripts. 

*External Script*
'Is actually best practice, as it keeps your HTML neat and imagine if you have 200 lines of js-script, it will be horrible to write all those scripts in your HTML file. Just like you do with CSS, it's always better to put it in a different file and reference it.

**Comment by ifiokabasibom** [comment]
alright, thanks for the help. i appreciate
